name: Prod Deployment

on:
  push:
    branches: [ stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Stage
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: stage
    
    - name: Push changes - Init Prod
      run: git push origin -f stage:prod 
 